# Generated by Django 3.1.2 on 2023-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(blank=True, default='Sensor', max_length=200),
        ),
    ]
