# Generated by Django 3.1.2 on 2023-06-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20230605_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(default='Sensor', max_length=200),
        ),
    ]
